import { useReducer } from "react";
import { MainContext } from "@/store/MainContext";
import Head from "next/head";
import { initialState } from "@/store/MainContext";
import CardList from "@/components/CardList";
import styles from "@/styles/Home.module.css";

export default function Home() {
  const [state, dispatch] = useReducer(MainContext, { initialState });
  // const [tododata, setTodoTata ] = usestate({initialState})
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainContext.Provider value={initialState}>
        <main className={styles.Home}>
          <CardList />
        </main>
      </MainContext.Provider>
    </>
  );
}
