import Head from "next/head";
import { app } from "../plugnis/firebase";

import CardList from "@/components/CardList";
import styles from "@/styles/Home.module.scss";

export default function Home() {
  console.log(app);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.Home}>
        <CardList />
      </main>
    </>
  );
}
